
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siulqmtemsnbtosmthci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpdWxxbXRlbXNuYnRvc210aGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNjg1NTgsImV4cCI6MjA1Nzc0NDU1OH0.t7eTdUYdx6jAmX-n2-2ICIiZ1sidUNus63cj4rwudng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
